### ISSUE TITLE
Add SEO beneficial tags

### ISSUE THREAD

**Issue by GruelingPine185** [devkennyy/rungeon#118]
There are a few tags that are pleasing to search engines and crawlers. They are used to rank results to users. Right now, we don't have anything but the title tag. Let's fix that so that way the world will know Rungeon exists.

**Comment by GruelingPine185** [comment]
Awesome! So I do have one slight concern: for modern browsers the use of metatag keywords shouldn't be used. The reason being that it was often abused to get a higher rating on search engines.nowadays, keywords are somewhere between completely useless (engines disregard its presence) and counterintuitive (hurts SEO rather than helps it). If rungeon eventually gets a landing page with written content, we can use some of the keywords there rather than having them be metatags.

**Comment by devkennyy** [comment]
Alright, thanks for clearing that up.

**Comment by GruelingPine185** [comment]
It will do. It's not necessary at all tbh. Just a heads up
