### ISSUE TITLE
404 page doesn't fit style

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#125]
This page was automatically generated by Firebase and needs modifying. Should have the same style as the main site (color pallete, font-size etc.)

**Comment by staranbeer** [comment]
hey! i would like to work on this issue. but because of the themes on the website, does the page have to match the theme or just a generic page with global styles applied would do. thanks

**Comment by GruelingPine185** [comment]
Hello, you should use the themes available on the main page (localhost:3000/index.html). There are 7 of them including the default theme. There is a file called `themes.js` and there is a function that may be of interest: `setTheme()`. Essentially all it does is change the `theme-xxx` class in the `#body` and all elements inside the body tags will be updated. This functionality is pretty new, so it may have some issues here and there. If you need anything or have any questions feel free to comment below

**Comment by Aspireve** [comment]
Hey @devkennyy I have an idea for a 404 page based on your websites theme, should I post it?

**Comment by devkennyy** [comment]
Closed by [#129]
