### ISSUE TITLE
classes getting added instead of being replaced.

### ISSUE THREAD

**Issue by staranbeer** [devkennyy/rungeon#139]
![AwesomeScreenshot-26_7_2022,2 51 42pm](https://user-images.githubusercontent.com/62498540/180973718-8aa55870-9cd0-49ab-beeb-df8ffadc001b.gif)

on the index.html page, when i change the theme, instead of classes getting replaced the classes are being added one after the other.

**Comment by devkennyy** [comment]
I see! I was trying to see why this wasn't working. Would you like to try a solve?

**Comment by staranbeer** [comment]
sure!

**Comment by devkennyy** [comment]
Make sure you are making changes to the `stage-remake` branch, thank you!

**Comment by staranbeer** [comment]
yes i will do that although i have a question. is main.js going to be used in the rungeon.html file on the stage-remake branch?

**Comment by GruelingPine185** [comment]
@staranbeer on the `stage-remake` branch (and now the main branch) `rungeon.html` is now `rungeon.ejs`. rungeon.ejs relies on `game.js` not `main.js`. To my knowledge, only the index.html/index.ejs files use the main.js file.

**Comment by GruelingPine185** [comment]
I don't have this problem on the `main` or `stage-remake` branches. Which branch are you experiencing this issue on?

**Comment by staranbeer** [comment]
yeah i think this was an issue with the index.html file before ejs was added.

**Comment by GruelingPine185** [comment]
Alright. Let me know if it occurs again and I'll reopen the issue
