### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by E-fais** [devkennyy/rungeon#159]
Live demo link not working.

![CA724910-8418-4640-99CA-30EDF488F949](https://user-images.githubusercontent.com/102040088/194068806-4b64cb7c-7fc8-42e8-a987-ec149ee8bb4c.jpeg)

**Comment by devkennyy** [comment]
I'm aware of this, I'm just not sure how to fix it.

**Comment by E-fais** [comment]
If this is a javascript front end app, you can try hosting in netlify. It is simple :)
