### ISSUE TITLE
Make site responsive

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#161]
Accesibile to Mobile users.

**Comment by devkennyy** [comment]
Most likely, the path just needs to be changed.

**Comment by devkennyy** [comment]
Also, the lock and key on level 4 doesn't work on mobile.

**Comment by Shabbyconnor** [comment]
The fix from 2a32c382b4055eb81c79b69b558796b099d8f188 works great! Anything else we need to do before closing this issue?

**Comment by devkennyy** [comment]
Nope, thanks for reminding me :)
