### ISSUE TITLE
Backend?

### ISSUE THREAD

**Issue by 0xRenegade** [devkennyy/rungeon#36]
Has a backend for this been considered? I'd be interested in contributing if there was plans for one. ^_^

**Comment by devkennyy** [comment]
An account system would make it easier to store data, do you have any other reasons for a backend?

**Comment by 0xRenegade** [comment]
in it's current form, it's not necessary. but things like accounts and even tracking session and having the backend determine what 'stage' the game is at.

**Comment by Andreu-G** [comment]
Would also be interesting to track achievements too.

**Comment by devkennyy** [comment]
And we wouldn't have to save theme data in local storage. A backend sounds feasible, did you have anything particular in mind?

**Comment by 0xRenegade** [comment]
I'm open to PHP or JS backend, whichever works for everyone the best.

- Lightweight PHP Framework: https://www.codeigniter.com/

- Not as lightweight, but very good for scaling up to a more complex game if that is what happens here: https://feathersjs.com/ Node.js framework

**Comment by devkennyy** [comment]
Which are you more comfortable with? Personally I think we should go with Node.js, would love to hear others thoughts.

**Comment by 0xRenegade** [comment]
More used to using PHP, but I know JS and node.js well enough I think I could handle using feathers. Same principles apply from PHP, just get to know the framework well enough to know what it can do and apply it. Plus I would enjoy having some real-world experience to show for on the JS backends.

**Comment by devkennyy** [comment]
That's good to hear. Keep me posted 👍

**Comment by GruelingPine185** [comment]
closes #36
