### ISSUE TITLE
Separate JS into modules

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#39]
`src > frontend > js `

Separate functions into modules for example `stage-controller.js`

**Comment by aymanesarrar** [comment]
can i take the issue ?

**Comment by devkennyy** [comment]
Of course, I've assigned you :)

**Comment by aymanesarrar** [comment]
there is a problem, we can't re assign an exported variable

**Comment by devkennyy** [comment]
Can you elaborate? Which line are you talking about?

**Comment by aymanesarrar** [comment]
i did some functions to assign them, can you check if your game is working please

**Comment by devkennyy** [comment]
As I mentioned in the pull request, I can't navigate to the game through index.html - the function the doors have doesn't run.

**Comment by aymanesarrar** [comment]
i'm on it

**Comment by devkennyy** [comment]
Keep me posted :)

**Comment by aymanesarrar** [comment]
yo can we talk on discord ?

**Comment by devkennyy** [comment]
That's fine by me, have you joined the [Discord](https://discord.gg/SFX2KSuzep)?
