### ISSUE TITLE
A little hard to tell if a button is disabled for mobile

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#61]

**Comment by Aspireve** [comment]
Hey!! @devkennyy I guess I found a solution
You could set the button text for the first-stage to "bugs" eg-
![image](https://user-images.githubusercontent.com/93852415/179347109-cb9a7620-edfa-4ecb-b80d-dd0b52b1de51.png)
and then after completing the task the button changes to 
![image](https://user-images.githubusercontent.com/93852415/179347139-0c2b2e24-09a5-46cd-b735-b5a6a48839fc.png)

And others can be done similarly
Should I go ahead with it?

**Comment by devkennyy** [comment]
Oops! I accidentally edited your comment instead of adding a new one 😭

This is a creative fix and I'm down for it. Do you mind clearing up which stages you would be doing this for and what you would be replacing?

**Comment by Aspireve** [comment]
Yup Sure!! Ill send the screenshots and images as soon as I can, also I'll share the pull request so you can check all the changes I made to the codebase

**Comment by devkennyy** [comment]
I appreciate that! Thank you so much @Aspireve

**Comment by Aspireve** [comment]
Hey @devkennyy, Thanks!!
This is exactly what I did, Sorry for a bit laggy video though. Hope you like it!! 

https://user-images.githubusercontent.com/93852415/179349146-4511e367-ef67-4bf1-ae44-d3b8290fff2e.mp4

**Comment by devkennyy** [comment]
I like it! They're subtle hints. I do feel that the dragon one is a little long. Perhaps change it like so:
"You do have that Coin, right?" => "Where's that coin?"

Everything else looks _chefs kiss_ 👍

**Comment by Aspireve** [comment]
Oh I pushed the older file, Ill create another pull request

**Comment by Aspireve** [comment]
Yes the latest one is the correct one!!
Happy to Help!!

**Comment by devkennyy** [comment]
This will do for now but I think a simple visual change would be the most effective. The more text, the more we drift away from the minimalistic aspect.

**Comment by staranbeer** [comment]
hey! we can also target the disabled pseudo class of the button element and add a brightness filter to make the disabled state much more effective. 
here i've set the brightness to 70%. 

![image](https://user-images.githubusercontent.com/62498540/180644346-10be0672-d389-4172-b86a-8a1e7979d761.png)

**Comment by devkennyy** [comment]
That does look more effective. Do you think you can revert the previous changes aswell?

**Comment by staranbeer** [comment]
revert the previous changes?

**Comment by devkennyy** [comment]
The ones mentioned above. This is the [pull request](https://github.com/devkennyy/rungeon/pull/71).

**Comment by staranbeer** [comment]
okay sure! but i am new to the open source community so i dont really know how. do i have to manually edit out the code that was added with the commit or is there a better way to do this?

**Comment by devkennyy** [comment]
Since we've edited the code afterwards you'll have to do it manually. There is normally an automatic revert though.

**Comment by staranbeer** [comment]
just a suggestion: isn't it a bit better for the button text to change to continue when the task is completed, we can use the brightness hack on top of it to make the the button look unusable.

**Comment by devkennyy** [comment]
I think the text isn't necessary with the brightness hack and will only require more reading. We could just have two states: "Locked", "Continue". Let me know what you think.

**Comment by staranbeer** [comment]
I agree that changing the brightness is pretty effective by itself however i still think getting proper visual feedback (text changing from abc to continue ) is better for the overall user experience but i totally get your point too so let me know what your final decision is.

**Comment by devkennyy** [comment]
While it may provide clarity, I feel as though there is too much going on. Make it say 'Locked' when disabled and we'll go from there. Thanks!
