### ISSUE TITLE
strictly use camelcase

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#74]
convert repo to camelcase (unless necessary). functions starting with an uppercase letter should only be used as a constructor

**Comment by Shabbyconnor** [comment]
Would you want underscores removed to conform to camelcase?

For example, would the function ```Reset_Stage(...)``` be rewritten as ```resetStage(...)``` or ```reset_Stage(...)```?

**Comment by devkennyy** [comment]
Yes please.
