### ISSUE TITLE
Theme popup modifications. 

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#90]
![image](https://user-images.githubusercontent.com/105208736/179453065-b61f3bba-e397-412c-ba6c-89667b4f174e.png)

The bottom margin should be increased and the height should be increased by roughly 1 pixel. Overall, this needs to be more responsive in case we add more popups. Maybe we should remove all the icons on the page? Would love to hear suggestions.

![image](https://user-images.githubusercontent.com/105208736/179453508-30e87ab6-7661-4211-b9c4-83acdaa27e32.png)

**Comment by knight-95** [comment]
i guess removing icons is not a good idea instead, we can work on adjusting the size of the content/margin

**Comment by devkennyy** [comment]
Alright, let me know what you come up with.

**Comment by devkennyy** [comment]
Can you add a few test themes and show what it would look like? Just the div, no styles.

**Comment by devkennyy** [comment]
I'm not sure this is the solution we should go for. I believe we should hide all 3 icons and centre the div.

**Comment by Trevy05** [comment]
A fixed dropdown menu with a scrollbar seems like the most logical solution.
