### ISSUE TITLE
Clicking a theme doesn't close popup

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#95]
We need to call the `toggleThemePopup` function in the `setTheme` function

**Comment by Davisralves** [comment]
Hi, can take this issue ?
I should do a pull request in my folk ?

**Comment by devkennyy** [comment]
> Hi, can take this issue ? I should do a pull request in my fork ?

Go ahead, I've assigned you 😊

**Comment by devkennyy** [comment]
The popup should close (call the function) after clicking a theme,
